# Labeler configuration for auto-labeling PRs based on file paths

'dependencies':
  - package.json
  - package-lock.json
  - 'package*.json'

'documentation':
  - '**/*.md'
  - 'docs/**/*'

'ci/cd':
  - '.github/workflows/**/*'
  - '.github/**/*'

'ai':
  - 'src/ai/**/*'
  - 'tests/ai/**/*'

'docker':
  - 'src/application/DockerManager.*'
  - 'tests/application/DockerManager.*'

'core':
  - 'src/application/**/*'
  - 'src/domain/**/*'

'cli':
  - 'src/cli/**/*'

'tests':
  - 'tests/**/*'
  - '**/*.test.ts'
  - '**/*.spec.ts'

'formatting':
  - 'src/formatters/**/*'

'types':
  - 'src/domain/models/**/*'
  - '**/*.d.ts'

'config':
  - 'tsconfig*.json'
  - 'jest.config.js'
  - '.eslintrc.json'
  - '.prettierrc.json'

