name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🔧 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '♻️ Refactoring'
    labels:
      - 'refactor'
      - 'refactoring'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
      - 'minor'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'patch'
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## Installation

  ```bash
  npm install -g @kitiumai/npm-package-tester@$RESOLVED_VERSION
  ```

  ## Contributors

  $CONTRIBUTORS

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'bug'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'feature'
    title:
      - '/feat/i'
      - '/feature/i'
  - label: 'chore'
    title:
      - '/chore/i'
  - label: 'dependencies'
    files:
      - 'package.json'
      - 'package-lock.json'

